----------------------------------------------------------------------------------------------------
id='e7adeafc-b7ba-41bf-b154-c8f95a22dc1e' source='user' models_usage=None metadata={} created_at=datetime.datetime(2025, 8, 12, 17, 43, 23, 545776, tzinfo=datetime.timezone.utc) content='Get time in New Delhi' type='TextMessage'
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
id='f56c2bfd-0662-4887-9cf7-de545dae4b9b' source='Agent' models_usage=RequestUsage(prompt_tokens=222, completion_tokens=18) metadata={} created_at=datetime.datetime(2025, 8, 12, 17, 43, 27, 93458, tzinfo=datetime.timezone.utc) content=[FunctionCall(id='call_TitwCW2cpoTv4qrweiGlwE1U', arguments='{"timezone":"Asia/Kolkata"}', name='get_current_time')] type='ToolCallRequestEvent'
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
id='c01e284d-bd7a-48b4-afae-8ebad29dffee' source='Agent' models_usage=None metadata={} created_at=datetime.datetime(2025, 8, 12, 17, 43, 27, 99252, tzinfo=datetime.timezone.utc) content=[FunctionExecutionResult(content='{\n  "timezone": "Asia/Kolkata",\n  "datetime": "2025-08-12T23:13:27+05:30",\n  "is_dst": false\n}', name='get_current_time', call_id='call_TitwCW2cpoTv4qrweiGlwE1U', is_error=False)] type='ToolCallExecutionEvent'        
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
id='9758528b-f5c0-45bb-af3b-538ee73f53e2' source='Agent' models_usage=RequestUsage(prompt_tokens=90, completion_tokens=21) metadata={} created_at=datetime.datetime(2025, 8, 12, 17, 43, 28, 602646, tzinfo=datetime.timezone.utc) content='The current time in New Delhi is 11:13 PM on August 12, 2025.' type='TextMessage'
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
messages=[TextMessage(id='e7adeafc-b7ba-41bf-b154-c8f95a22dc1e', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 8, 12, 17, 43, 23, 545776, tzinfo=datetime.timezone.utc), content='Get time in New Delhi', type='TextMessage'), ToolCallRequestEvent(id='f56c2bfd-0662-4887-9cf7-de545dae4b9b', source='Agent', models_usage=RequestUsage(prompt_tokens=222, completion_tokens=18), metadata={}, created_at=datetime.datetime(2025, 8, 12, 17, 43, 27, 93458, tzinfo=datetime.timezone.utc), content=[FunctionCall(id='call_TitwCW2cpoTv4qrweiGlwE1U', arguments='{"timezone":"Asia/Kolkata"}', name='get_current_time')], type='ToolCallRequestEvent'), ToolCallExecutionEvent(id='c01e284d-bd7a-48b4-afae-8ebad29dffee', source='Agent', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 8, 12, 17, 43, 27, 99252, tzinfo=datetime.timezone.utc), content=[FunctionExecutionResult(content='{\n  "timezone": "Asia/Kolkata",\n  "datetime": "2025-08-12T23:13:27+05:30",\n  "is_dst": false\n}', name='get_current_time', call_id='call_TitwCW2cpoTv4qrweiGlwE1U', is_error=False)], type='ToolCallExecutionEvent'), TextMessage(id='9758528b-f5c0-45bb-af3b-538ee73f53e2', source='Agent', models_usage=RequestUsage(prompt_tokens=90, completion_tokens=21), metadata={}, created_at=datetime.datetime(2025, 8, 12, 17, 43, 28, 602646, tzinfo=datetime.timezone.utc), content='The current time in New Delhi is 11:13 PM on August 12, 2025.', type='TextMessage')] stop_reason=None
----------------------------------------------------------------------------------------------------
